// SPDX-License-Identifier: MIT

#define PBIO_CONFIG_BATTERY                 (0)
#define PBIO_CONFIG_DCMOTOR                 (0)
#define PBIO_CONFIG_DCMOTOR_NUM_DEV         (1)
#define PBIO_CONFIG_DRIVEBASE_SPIKE         (0)
#define PBIO_CONFIG_IMU                     (0)
#define PBIO_CONFIG_LIGHT                   (0)
#define PBIO_CONFIG_LOGGER                  (1)
#define PBIO_CONFIG_MOTOR_PROCESS           (0)
#define PBIO_CONFIG_PORT                    (1)
#define PBIO_CONFIG_PORT_NUM_DEV            (1)
#define PBIO_CONFIG_PORT_DCM                (1)
#define PBIO_CONFIG_PORT_DCM_PUP            (1)
#define PBIO_CONFIG_PORT_DCM_EV3            (0)
#define PBIO_CONFIG_PORT_DCM_NUM_DEV        (1)
#define PBIO_CONFIG_PORT_LUMP               (1)
#define PBIO_CONFIG_PORT_LUMP_MODE_INFO     (1)
#define PBIO_CONFIG_PORT_LUMP_NUM_DEV       (1)
#define PBIO_CONFIG_PORT_LUMP_DIRECT_UART   (1)
#define PBIO_CONFIG_SERVO                   (1)
#define PBIO_CONFIG_SERVO_NUM_DEV           (1)
#define PBIO_CONFIG_SERVO_EV3_NXT           (0)
#define PBIO_CONFIG_SERVO_PUP               (1)
#define PBIO_CONFIG_SERVO_PUP_MOVE_HUB      (0)
#define PBIO_CONFIG_TACHO                   (0)

#define PBIO_CONFIG_ENABLE_SYS              (1)
